# Tell Spring Boot where the database is
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_db
# XAMPP default username is usually 'root'
spring.datasource.username=root
# XAMPP default password is usually blank (empty)
spring.datasource.password=

# Tell Spring to use the MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# THIS IS THE MAGIC LINE: It tells Spring to automatically create or update your database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Show the SQL commands in the terminal so you can see what Spring is doing behind the scenes
spring.jpa.show-sql=true

# Allow files up to 5MB each, and a total request size of 15MB (for 3 images)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB